language: cpp
install: make
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libglew-dev
  - sudo apt-get install libglfw3-dev
  - sudo apt-get install libsoil-dev
  - sudo apt-get install libglm-dev
  - sudo apt-get install llvm
