language: cpp
install: make
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libglew-dev
  - sudo apt-get install libglfw3-dev
  - sudo apt-get install libsoil-dev
  - sudo apt-get install libglm-dev
  - sudo apt-get install llvm
  - sudo apt-get install build-essential

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MG5hYm9zJTNBZ2xhcmdoLmZyLyUyMXJjV21kaVJYVEVKYkZ0RXd5eCUzQWdsYXJnaC5mcg"
    on_success: change # default: always
    on_failure: always # default: always
    on_start:   change # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always

